### ISSUE TITLE
boutons pills (réservation/new) : en format mobile bouton équipements trop petit (texte mal centré dans le bouton)

### ISSUE THREAD

**Issue by ThonyP** [WildCodeSchool/orleans-0218-labo#210]
boutons pills (réservation/new) : en format mobile bouton équipements trop petit (texte mal centré dans le bouton)

**Comment by 1A2Z3E4R** [comment]
boutons pills (réservation/new) : en format mobile bouton équipements trop petit (texte mal centré dans le bouton)
